# Generated by Django 3.2.12 on 2023-12-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField()),
            ],
        ),
    ]
