# Generated by Django 3.2.12 on 2024-01-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_ayushsilverplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ayushsilverplan',
        ),
    ]
