# Generated by Django 3.2.12 on 2024-01-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_ayushsilverplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayushsilverplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('t1', models.CharField(max_length=50)),
                ('t2', models.CharField(max_length=50)),
                ('t3', models.CharField(max_length=50)),
                ('t4', models.CharField(max_length=50)),
                ('t5', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.packages')),
            ],
        ),
    ]
