# Generated by Django 3.2.12 on 2024-01-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ayushsilverplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_blog',
        ),
    ]
