# Generated by Django 4.2.7 on 2024-01-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_subnewsevents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subnewsevents',
            old_name='description',
            new_name='descriptions',
        ),
    ]
