# Generated by Django 4.2.7 on 2024-01-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_description_subnewsevents_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booknow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('requirment', models.TextField()),
            ],
        ),
    ]
