# Generated by Django 4.2.7 on 2024-01-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_booknow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('location1', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
