a='lorem ipsum is a dumy text'
print(a.capitalize())
print(a.casefold())
print(a.count('e'))
print(a.isdigit())
print(a.islower())
print(a.upper())
print(a.lower())
print(a.split())
print(a.swapcase())
print(a.isalnum())
